[package]
name = "provision"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.10.4"
ic-cdk = "0.16"
ic-cdk-macros = "0.16.0"
serde_bytes = "0.11.5"

serde = "1.0.152"
